apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      hostname: postgres
      containers:
      - name: postgres
        image: maikimaiko/postgres-multi-db:10
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-config  
          - secretRef:
              name: postgres-user-creds
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-pv
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc
